In [14]:
import pandas as pd
import numpy as np

In [15]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [16]:
tourney = pd.read_csv('data/raw/MNCAATourneyCompactResults.csv')
reg_season = pd.read_csv('data/raw/MRegularSeasonDetailedResults.csv')
teams = pd.read_csv('data/raw/MTeams.csv')

In [17]:
wins = reg_season[['Season', 'WTeamID', 'WScore', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR', 'WAst', 'WTO', 'WStl', 'WBlk', 'WPF']]
losses = reg_season[['Season', 'LTeamID', 'LScore', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3', 'LFTM', 'LFTA', 'LOR', 'LDR', 'LAst', 'LTO', 'LStl', 'LBlk', 'LPF']]

In [18]:
wins.columns = ['Season', 'TeamID', 'Score', 'FGM', 'FGA', 'FGM3', 'FGA3', 'FTM', 'FTA', 'OR', 'DR', 'Ast', 'TO', 'Stl', 'Blk', 'PF']
losses.columns = ['Season', 'TeamID', 'Score', 'FGM', 'FGA', 'FGM3', 'FGA3', 'FTM', 'FTA', 'OR', 'DR', 'Ast', 'TO', 'Stl', 'Blk', 'PF']

In [19]:
w_grouped = wins.groupby(['Season', 'TeamID']).aggregate(['sum', 'count'])
l_grouped = losses.groupby(['Season', 'TeamID']).aggregate(['sum', 'count'])

In [20]:
w_grouped.columns = ['_'.join(map(str, col)) for col in w_grouped.columns.values]
l_grouped.columns = ['_'.join(map(str, col)) for col in l_grouped.columns.values]

In [21]:
w_grouped = w_grouped[['Score_sum', 'FGM_sum', 'FGA_sum', 'FGM3_sum', 'FGA3_sum', 'FTM_sum', 'FTA_sum', 'OR_sum','DR_sum', 'Ast_sum', 'TO_sum', 'Stl_sum', 'Blk_sum', 'PF_sum', 'PF_count']]
w_grouped.columns = ['Points', 'FGM', 'FGA', 'FGM3', 'FGA3','FTM', 'FTA', 'OR','DR', 'Ast', 'TO','Stl', 'Blk', 'PF', 'Games']
l_grouped = l_grouped[['Score_sum', 'FGM_sum', 'FGA_sum', 'FGM3_sum', 'FGA3_sum', 'FTM_sum', 'FTA_sum', 'OR_sum','DR_sum', 'Ast_sum', 'TO_sum', 'Stl_sum', 'Blk_sum', 'PF_sum', 'PF_count']]
l_grouped.columns = ['Points', 'FGM', 'FGA', 'FGM3', 'FGA3','FTM', 'FTA', 'OR','DR', 'Ast', 'TO','Stl', 'Blk', 'PF', 'Games']

In [36]:
reg_season_stats = w_grouped.add(l_grouped, fill_value = 0)

In [25]:
reg_season_stats = reg_season_stats.reset_index(drop = False)

In [140]:
reg_season_stats = reg_season_stats.dropna().reset_index(drop = True)

In [141]:
for c in ['Points', 'FGM', 'FGA', 'FGM3', 'FGA3', 'FTM', 'FTA', 'OR', 'DR', 'Ast', 'TO', 'Stl', 'Blk', 'PF']:
    reg_season_stats[c] = reg_season_stats[c] / reg_season_stats['Games']

In [142]:
reg_season_stats

,Season,TeamID,Points,FGM,FGA,FGM3,FGA3,FTM,FTA,OR,DR,Ast,TO,Stl,Blk,PF,Games
0,2003,1102,57.250000,19.142857,39.785714,7.821429,20.821429,11.142857,17.107143,4.178571,16.821429,13.000000,11.428571,5.964286,1.785714,18.750000,28.0
1,2003,1103,78.777778,27.148148,55.851852,5.444444,16.074074,19.037037,25.851852,9.777778,19.925926,15.222222,12.629630,7.259259,2.333333,19.851852,27.0
2,2003,1104,69.285714,24.035714,57.178571,6.357143,19.857143,14.857143,20.928571,13.571429,23.928571,12.107143,13.285714,6.607143,3.785714,18.035714,28.0
3,2003,1105,71.769231,24.384615,61.615385,7.576923,20.769231,15.423077,21.846154,13.500000,23.115385,14.538462,18.653846,9.307692,2.076923,20.230769,26.0
4,2003,1106,63.607143,23.428571,55.285714,6.107143,17.642857,10.642857,16.464286,12.285714,23.857143,11.678571,17.035714,8.357143,3.142857,18.178571,28.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8330,2026,1477,67.066667,23.433333,55.800000,8.066667,25.800000,12.133333,17.866667,7.400000,21.766667,14.633333,12.566667,6.733333,3.133333,16.900000,30.0
8331,2026,1478,72.322581,24.709677,54.129032,7.580645,22.096774,15.322581,21.354839,7.000000,24.903226,13.967742,12.451613,5.483871,3.290323,17.483871,31.0
8332,2026,1479,68.250000,25.750000,57.906250,5.781250,18.000000,10.968750,14.812500,7.437500,21.437500,13.968750,8.625000,6.968750,3.843750,18.375000,32.0
8333,2026,1480,75.333333,27.766667,62.900000,6.866667,20.733333,12.933333,18.366667,10.033333,23.100000,12.300000,10.700000,6.366667,4.666667,17.233333,30.0
8334,2026,1481,61.464286,21.928571,51.357143,6.178571,20.464286,11.428571,16.285714,5.785714,21.107143,10.892857,10.357143,6.035714,2.035714,14.142857,28.0

In [174]:
round1_tourney = tourney[tourney['DayNum'].isin([136,137])].reset_index(drop = True)

In [175]:
tourney_winners = round1_tourney[['Season', 'WTeamID']].merge(reg_season_stats, left_on = ['Season', 'WTeamID'], right_on = ['Season', 'TeamID'], how = 'inner')

In [176]:
tourney_winners['Target'] = 1

In [177]:
tourney_losers = round1_tourney[['Season', 'LTeamID']].merge(reg_season_stats, left_on = ['Season', 'LTeamID'], right_on = ['Season', 'TeamID'], how = 'inner')

In [178]:
tourney_losers['Target'] = 0

In [179]:
tourney_winners = tourney_winners.drop('WTeamID', axis = 1)
tourney_losers = tourney_losers.drop('LTeamID', axis = 1)

In [180]:
data = pd.concat([tourney_winners, tourney_losers])

In [182]:
data = data.reset_index(drop = True)

In [184]:
teams

     TeamID        TeamName  FirstD1Season  LastD1Season
0      1101     Abilene Chr           2014          2026
1      1102       Air Force           1985          2026
2      1103           Akron           1985          2026
3      1104         Alabama           1985          2026
4      1105     Alabama A&M           2000          2026
..      ...             ...            ...           ...
376    1477  East Texas A&M           2023          2026
377    1478        Le Moyne           2024          2026
378    1479      Mercyhurst           2025          2026
379    1480    West Georgia           2025          2026
380    1481       New Haven           2026          2026

[381 rows x 4 columns]

In [185]:
data['Team'] = data['TeamID'].map(teams.set_index('TeamID')['TeamName'].to_dict())

In [187]:
data.columns

Index(['Season', 'TeamID', 'Points', 'FGM', 'FGA', 'FGM3', 'FGA3', 'FTM',
       'FTA', 'OR', 'DR', 'Ast', 'TO', 'Stl', 'Blk', 'PF', 'Games', 'Target',
       'Team'],
      dtype='str')

In [188]:
data = data[['Team', 'TeamID', 'Season', 'Points', 'FGM', 'FGA', 'FGM3', 'FGA3', 'FTM','FTA', 'OR', 'DR', 'Ast', 'TO', 'Stl', 'Blk', 'PF', 'Games', 'Target']]

In [189]:
data

,Team,TeamID,Season,Points,FGM,FGA,FGM3,FGA3,FTM,FTA,OR,DR,Ast,TO,Stl,Blk,PF,Games,Target
0,Arizona,1112,2003,85.214286,30.321429,65.714286,7.035714,20.071429,17.535714,25.000000,15.178571,27.642857,17.642857,14.785714,8.464286,4.214286,17.750000,28.0,1
1,Arizona St,1113,2003,75.965517,27.206897,56.896552,4.000000,12.586207,17.551724,26.206897,13.689655,23.310345,15.551724,14.000000,5.206897,4.241379,19.413793,29.0,1
2,C Michigan,1141,2003,79.344828,26.620690,52.689655,6.827586,17.931034,19.275862,25.172414,10.586207,23.275862,15.620690,18.241379,7.103448,4.000000,20.965517,29.0,1
3,California,1143,2003,74.482759,27.344828,58.724138,6.413793,17.034483,13.379310,19.517241,11.241379,24.379310,16.000000,14.172414,6.551724,2.793103,17.103448,29.0,1
4,Connecticut,1163,2003,80.033333,29.533333,62.200000,6.066667,15.700000,14.900000,22.100000,14.766667,27.900000,15.633333,15.800000,5.933333,7.733333,18.400000,30.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1377,Bryant,1136,2025,80.343750,29.312500,64.875000,7.531250,22.562500,14.187500,19.750000,11.750000,25.843750,14.281250,11.781250,6.625000,6.031250,16.093750,32.0,0
1378,North Carolina,1314,2025,80.800000,28.714286,60.285714,7.885714,22.314286,15.485714,21.000000,7.857143,25.428571,14.657143,10.542857,5.885714,3.714286,16.771429,35.0,0
1379,Marquette,1266,2025,76.878788,27.848485,62.545455,9.393939,28.939394,11.787879,16.303030,9.242424,21.848485,13.787879,8.939394,9.030303,3.696970,15.969697,33.0,0
1380,Liberty,1251,2025,74.354839,26.580645,54.225806,10.225806,25.870968,10.967742,16.774194,5.000000,23.677419,16.258065,9.612903,6.096774,2.967742,14.032258,31.0,0
1381,Vanderbilt,1435,2025,79.625000,27.906250,61.843750,8.093750,24.875000,15.718750,21.031250,9.875000,21.625000,13.968750,9.781250,9.031250,3.968750,17.968750,32.0,0

In [190]:
data

,Team,TeamID,Season,Points,FGM,FGA,FGM3,FGA3,FTM,FTA,OR,DR,Ast,TO,Stl,Blk,PF,Games,Target
0,Arizona,1112,2003,85.214286,30.321429,65.714286,7.035714,20.071429,17.535714,25.000000,15.178571,27.642857,17.642857,14.785714,8.464286,4.214286,17.750000,28.0,1
1,Arizona St,1113,2003,75.965517,27.206897,56.896552,4.000000,12.586207,17.551724,26.206897,13.689655,23.310345,15.551724,14.000000,5.206897,4.241379,19.413793,29.0,1
2,C Michigan,1141,2003,79.344828,26.620690,52.689655,6.827586,17.931034,19.275862,25.172414,10.586207,23.275862,15.620690,18.241379,7.103448,4.000000,20.965517,29.0,1
3,California,1143,2003,74.482759,27.344828,58.724138,6.413793,17.034483,13.379310,19.517241,11.241379,24.379310,16.000000,14.172414,6.551724,2.793103,17.103448,29.0,1
4,Connecticut,1163,2003,80.033333,29.533333,62.200000,6.066667,15.700000,14.900000,22.100000,14.766667,27.900000,15.633333,15.800000,5.933333,7.733333,18.400000,30.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1377,Bryant,1136,2025,80.343750,29.312500,64.875000,7.531250,22.562500,14.187500,19.750000,11.750000,25.843750,14.281250,11.781250,6.625000,6.031250,16.093750,32.0,0
1378,North Carolina,1314,2025,80.800000,28.714286,60.285714,7.885714,22.314286,15.485714,21.000000,7.857143,25.428571,14.657143,10.542857,5.885714,3.714286,16.771429,35.0,0
1379,Marquette,1266,2025,76.878788,27.848485,62.545455,9.393939,28.939394,11.787879,16.303030,9.242424,21.848485,13.787879,8.939394,9.030303,3.696970,15.969697,33.0,0
1380,Liberty,1251,2025,74.354839,26.580645,54.225806,10.225806,25.870968,10.967742,16.774194,5.000000,23.677419,16.258065,9.612903,6.096774,2.967742,14.032258,31.0,0
1381,Vanderbilt,1435,2025,79.625000,27.906250,61.843750,8.093750,24.875000,15.718750,21.031250,9.875000,21.625000,13.968750,9.781250,9.031250,3.968750,17.968750,32.0,0

In [41]:
import etl

In [42]:
q = etl.get_data()